Traceback (most recent call last):
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.optimize import fsolve
def equations(p):
    L,V = p
    return (100 - (L+V), 0.4*100-0.1*L-0.8*V) #each equation is set so that it is equal to zero, also the returned value is also a tuple

L,V =  fsolve(equations, (1,1))
print(f'The solution is {L:0.2f} for L and {V:0.2f} for V')
print(type((L,V)),type((1,1)))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01moptimize[39;00m [38;5;28;01mimport[39;00m fsolve
[1;32m      2[0m [38;5;28;01mdef[39;00m [38;5;21mequations[39m(p):
[1;32m      3[0m     L,V [38;5;241m=[39m p

[0;31mModuleNotFoundError[0m: No module named 'scipy'

