Traceback (most recent call last):
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/clintguymon/opt/anaconda3/envs/jupyterbook2/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np #import the numpy library
import matplotlib.pyplot as plt #import the matplotlib library for plotting (also check out seaborn)
mVols = np.linspace(0.01,0.1,100) #create an array of molar volumes 
temps = [300,400,500] #create a list of temperatures in Kelvin
for each in temps:
    plt.plot(mVols,pressure_IG(each,mVols)/1000,label=f'{each} K') #plot the pressure as a function of molar volume
plt.title('Ideal Gas Pressure') #add a title to the plot
plt.xlabel('Molar Volume (m$^3$/mol)') #label the x-axis
plt.ylabel('Pressure (kPa)') #label the y-axis
plt.legend(); plt.show() #show the legend and the plot
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m [38;5;66;03m#import the numpy library[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m [38;5;66;03m#import the matplotlib library for plotting (also check out seaborn)[39;00m
[1;32m      3[0m mVols [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0.01[39m,[38;5;241m0.1[39m,[38;5;241m100[39m) [38;5;66;03m#create an array of molar volumes [39;00m

[0;31mModuleNotFoundError[0m: No module named 'numpy'

